name: CI

on:
  push:
    branches: [ main ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install Dependencies
        run: npm i
        
      - name: Build
        run: npm run build
      
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /ci
          remote_host: ${{secrets.SSH_HOST}}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
