name: CI

on:
  push:
    branches: [ main ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install Dependencies
        run: npm i
        
      - name: Build
        run: npm run build
        
      - name: Copy files with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./src"
          REMOTE_HOST: ${{secrets.SSH_HOST}}
          REMOTE_USER: ${{secrets.SSH_USER}}
          EXCLUDE: "/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh"
